# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build packages with Gradle

on:
  push:
    branches:
      - main

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run JPackage with Gradle
      run: ./gradlew jpackage
    - uses: actions/upload-artifact@v2
      with:
        name: macOS
        path: build/jpackage
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle　
    - name: Run JPackage with Gradle
      run: .\gradlew jpackage --no-daemon
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: build\jpackage
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run JPackage with Gradle
      run: ./gradlew jpackage
    - uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: build/jpackage
